export const ADD_FORM = "ADD_FORM"
export const DELETE_FORM = "DELETE_FORM"

export const ADD_QUESTION = 'ADD_QUESTION'
export const UPDATE_FORM = "UPDATE_FORM"
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'

export const ADD_OPTION = 'ADD_OPTION'
